### ISSUE TITLE
Screenshot capability is not included in extensions framework

### ISSUE THREAD

**Issue by zwaap** [Microsoft/AppCenter-Test-XCUITest-Extensions#7]
The App Center documentation states that the ability to take screenshots is provided by App Center's XCUITest extensions framework ([here](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/xcuitest)).  The code examples linked to in the doc use a class called `AppScreenshotter` for this functionality (see [here](https://github.com/Microsoft/AppCenter-Test-XCUITest-Extensions/blob/master/TestApp/Tests/UI/ACTLabelTest.swift#L25) and [here](https://github.com/Microsoft/AppCenter-Test-XCUITest-Extensions/blob/master/TestApp/Tests/UI/ACTLabelTest.m#L61)), but this class's implementation appears to be included in the test app rather than the framework ([here](https://github.com/Microsoft/AppCenter-Test-XCUITest-Extensions/blob/master/TestApp/Tests/UI/ACTScreenshotter.h)).  Attempting to reference `ACTScreenshotter` in an XCUITest that imports `AppCenterXCUITestExtensions` thus yields an "unresolved identifier" error.

**Comment by jmoody** [comment]
`ACTScreenshotter` is an example of how to take screenshots _without using the App Center XCUITest extension framework_.

We plan to remove the requirement that users link the AppCenterXCUITestExtension .framework in order to run tests in App Center.

The `ACTScreenshotter` class is part of documenting the transition away from this extension to Apple's native XCTestContext.

> The App Center documentation states that the ability to take screenshots is provided by App Center's XCUITest extensions framework (here). The code examples linked to in the doc use a class called AppScreenshotter for this functionality (see here and here)

Until we enable extension-less XCUITest support in AppCenter, use the `label` methods provided by this extension.

* https://github.com/Microsoft/AppCenter-Test-XCUITest-Extensions/blob/master/Sources/ACTLabel.h

**Comment by zwaap** [comment]
@jmoody thanks for the explanation - good to know that the need for the dependency is being removed.  Could the doc be updated in the meantime?  Right now it states that one of the things the extensions library does is provide screenshot-taking functionality, and it doesn't do that.

**Comment by jmoody** [comment]
The `label` methods take a screenshot.
